name: .NET Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore BrightHRUITests.sln

      - name: Build solution
        run: dotnet build BrightHRUITests.sln --configuration Release --no-restore

      - name: Install Playwright Browsers
        run: |
          dotnet tool restore
          pwsh ./bin/Release/net8.0/playwright.ps1 install

      - name: Run tests
        run: dotnet test BrightHRUITests.sln --configuration Release --no-build --verbosity normal
