name: .NET Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: BrightHRUITests/BrightHRUITests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ../../BrightHRUITests.sln

      - name: Build solution
        run: dotnet build ../../BrightHRUITests.sln --configuration Debug --no-restore

      - name: List build output folder
        run: ls -la ./bin/Debug/net8.0/

      - name: Install Playwright Browsers
        shell: pwsh
        run: ./bin/Debug/net8.0/playwright.ps1 install

      - name: Run tests
        run: dotnet test ../../BrightHRUITests.sln --configuration Debug --no-build --verbosity normal

